version: '3'
services:
    jekyll:
        environment:
          - JEKYLL_ENV=docker
        image: jekyll/jekyll:latest
        container_name: thedavecarroll-com
        command: >
          bash -c "jekyll clean --destination ./docs
          && jekyll serve --force_polling --watch --port 4000 --config _config.yml,_config.docker.yml --destination ./docs --drafts --future --incremental"
        ports:
          - "4000:4000"
        volumes:
          - C:\\GitHub\\thedavecarroll.com:/srv/jekyll
          - C:\\Docker\\Images\\jekyll\\bundle:/usr/local/bundle