#!/usr/bin/env bash
set -e # halt script on error

echo
echo "------------------------------------------------------------------------------------------------------------------------"
echo
if [ "$TRAVIS_PULL_REQUEST" != "false" -a "$TRAVIS_BRANCH" == "comments" ]; then

    echo "Building site for pull request for $TRAVIS_BRANCH..."
    echo
    bundle exec jekyll build --config _config.yml --source . --destination ./docs
    echo "Site built into /docs"

elif [ "$TRAVIS_BRANCH" == "main" ]; then

    echo "Building site for $TRAVIS_BRANCH..."
    echo
    bundle exec jekyll build --config _config.yml --source . --destination ./docs
    echo "Site built into /docs"

else

    echo "Build not triggered internally"
    echo
    echo "------------------------------------------------------------------------------------------------------------------------"
    exit 0

fi

echo
echo "------------------------------------------------------------------------------------------------------------------------"
echo
echo "Proofing links"
bundle exec htmlproofer ./docs --disable-external --allow_hash_href
echo "Proofing links complete"
echo
echo "------------------------------------------------------------------------------------------------------------------------"

exit 0